version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - db
    networks:
      - internalnetwork

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
        DB_HOST: "db"
        DB_PORT: 3306
        DB_USER: "root"
        DB_PASSWORD: "root"
        DB_NAME: "faculty_reg"
    depends_on:
      - db
    networks:
      - internalnetwork

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "faculty_reg"
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
        - internalnetwork

networks:
 internalnetwork:
  driver: bridge
volumes:
  data:

